[package]
name = "tasks"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
clap.workspace = true
devenv.workspace = true
serde_json.workspace = true
tokio.workspace = true
