[package]
name = "devenv"
version = "1.3.0"
edition.workspace = true
license.workspace = true

# Make `cargo run` default to the devenv CLI
default-run = "devenv"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap.workspace = true
cli-table.workspace = true
console = "0.15.8"
dotlock.workspace = true
fs2.workspace = true
hex.workspace = true
include_dir.workspace = true
indoc.workspace = true
miette.workspace = true
nix.workspace = true
devenv-eval-cache.workspace = true
petgraph = "0.6.5"
regex.workspace = true
reqwest.workspace = true
schemars.workspace = true
schematic.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true
sha2.workspace = true
sqlx.workspace = true
tempdir.workspace = true
tempfile = "3.12.0"
thiserror = "1.0.63"
tokio.workspace = true
tracing.workspace = true
which.workspace = true
whoami.workspace = true
xdg.workspace = true

[dev-dependencies]
pretty_assertions = { version = "1.4.0", features = ["unstable"] }
test-log = { version = "0.2.16", features = ["trace"] }
